### ISSUE TITLE
VM template need to support port forward from a specific interface

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/0-templates#100]
When you do a port fowrard
```
port
ip:port
interface_name:port
```
It's already supported by zero-os, but not the template. Let's see the best way to integrate it.

**Comment by xmonader** [comment]
Done: 
Add utils test case for allowed portforwards patterns
https://github.com/threefoldtech/jumpscale_lib/blob/development_portforwards_vmtemplate/JumpscaleLib/sal_zos/utils/Utils_test.py

(Not sure how to validate interface name )
https://github.com/threefoldtech/jumpscale_lib/blob/development_portforwards_vmtemplate/JumpscaleLib/sal_zos/vm/ZOS_VM.py#L131


I found the change will break the code interface here
https://github.com/threefoldtech/jumpscale_lib/blob/development_portforwards_vmtemplate/JumpscaleLib/sal_zos/vm/ZOS_VM.py#L292

There's a `drop_ports` method on ZOS_VM that calls `nft.drop_ports` which breaks the interface
https://github.com/threefoldtech/jumpscale_lib/blob/development/JumpscaleLib/clients/zero_os_protocol/Nft.py#L34
```
    _port_chk = typchk.Checker({
        'port': int,
        'interface': typchk.Or(str, typchk.IsNone()),
        'subnet': typchk.Or(str, typchk.IsNone()),
    })
```

**Comment by zaibon** [comment]
Found that we already can create/remove portforward  for container/vm. So I've what I need already, closing this one
