### ISSUE TITLE
Farmer robot capacity planning templates

### ISSUE THREAD

**Issue by FastGeert** [threefoldtech/0-templates#103]
### capacity_registration template
Instances of this template are created by the node templates (node robot)
This template takes care of storing the capacity of a node in its model.

**Model**
  - nodeid
  - node robot address
  - total SSD capacity
  - total HDD capacity
  - total memory capacity
  - used SSD capacity
  - used HDD capacity
  - used memory capacity
  - reserved SSD capacity
  - reserved HDD capacity
  - reserved memory capacity

**Actions:**
- *update_capacity* This action stores the capacity of a certain node in its model. Parameters:
  - total SSD capacity
  - total HDD capacity
  - total memory capacity
  - used SSD capacity
  - used HDD capacity
  - used memory capacity
- *validate_reservation* This action validates if the reservation is valid and returns the type and size of the reservation. This action is used by the node robot to validate a deployment request. Parameters:
  - reservation service guid
  - reservation ticket

### capacity_reservation template
Instances of this template are created by the DM templates (DM robot)

**Model**
- type (memory / ssd / hdd)
- size
- anti_affinity (list of node-ids that cannot be assigned for this reservation)
- address (not to be set at creation. Blockchain address to which funds need to be transfered to. Is a new address that needs to be generated when the service is created.)
- status (not to be set at creation. [modeled / paid / assigned])
- node-id (not be set at creation. Is calculated by the template)
- reservation-ticket (not to be set at creation)

**Actions**
- *get_address* Returns the wallet address to which funds need to be wired to and the amount of funds.
- *monitor_address* Checks if funds have been transfered. Puts the reservation into paid if funds arrived.
- *assign* Calculates, stores & returns the node-id & reservation-ticket. Raises an error if the status != paid. If it already is assigned, it just returns the node-id & reservation-ticket. The reservation-ticket is a generated secret that will be used by the node robot to validate the reservation. Assignments are also added to the capacity_registration templates, so that future capacity reservation requests can take into account that these reservations were made there.
- *re_assign* Recalculates the node-id in case the previous assignment needs to be replaced.

**Comment by despiegk** [comment]
there is another plan how to do this, please check with kristof
