### ISSUE TITLE
create traefik, coredns & etcd templates

### ISSUE THREAD

**Issue by BolaNasr** [threefoldtech/0-templates#113]
create 0-robot templates to install these components

**Comment by zaibon** [comment]
@BolaNasr let's start with the core template needed for this setup. 
So trakeik, coredns and etcd.

Each of these template needs to be "node" template, which means they are meant to be directly installed on a node. (example of such template are zerodb, namespaces, vm...)

Before you start writing anything, please write down here in the issue how you see the schema and the actions of each templates.

Then to create the flist, the way to go is to write a prefab module that build/install the programs and then create an flist out of it. So we have something repeatable to build these flists.

Once we have all this, ping me so we can review the spec of the template and continue with the implementation

**Comment by BolaNasr** [comment]
### Etcd
**schema of etcd :** 

```
struct Schema {
   name @0: Text;
   listen-peer-urls @1: Text;
   listen-client-urls @2 Text;
   initial-advertise-peer-urls @3: Text;
   advertise-client-urls @4: Text;
}
```
**actions**
```
install
uninstall
start
stop

```
### Traefik
**schema of traefik:**
```
struct Schema {
    user @0: Text 
    pass @1: Text
    endPoints @2 : List(Text)
   domain @3 :Text
    watch @4 : Bool=True
    address @5 : Text
    plugins @6 :List(Text)
}
```
**actions**
```
install
uninstall
start
stop
reload
configure
reset
```
### CoreDNS
**schema of coredns:**
```
struct Schema {
    zone @0: Text  // default "."
    password @1: Text  // default none 
}
```
**actions**
```
install
uninstall
start
stop
```

@zaibon **i think these are the schemas and the actions of each templates as far as i understood**

**Comment by zaibon** [comment]
```
struct Schema {
   name @0: Text; # why a name, service by itself already have a name
   listen-peer-urls @1: Text; # this looks like it needs to be a list
   listen-client-urls @2 Text;  # this looks like it needs to be a list
   initial-advertise-peer-urls @3: Text;  # this looks like it needs to be a list
   advertise-client-urls @4: Text;  # this looks like it needs to be a list
}
```
regarding this schema, I'm quite sure we'll never have the urls before deploying. So I think that requires more thinking. 

```
struct Schema {
    user @0: Text 
    pass @1: Text
    endPoints @2 : List(Text) # what is this ? endpoints to what ? needs to use more explicit names
   domain @3 :Text # same here, what domain ?
    watch @4 : Bool=True # I guess that's to tell if we need to watch etcd changes ?
    address @5 : Text # address of what ? need more explicit here too
    plugins @6 :List(Text) # is this needed at all ? We know our use case, so I think the plugins will be something hardoced
}

Can you give some more input about what these actions will do:
- reload
- configure
- reset


There is something I don't see is the link between these services. As far as I understand etcd is the source of configuration for both core dns and traefik, but I don't see any etcd client in the core dns or traefik schema. How are they going to know where to look for etcd ?

**Comment by BolaNasr** [comment]
### Etcd :
All these URLS it's something the user is supposed to provide 

### CoreDns and Traefik 
you are correct should add the name of an etcd client service and get Ip from it so we replace it to **etcd_server_name**

**Comment by serboctor** [comment]
@zaibon Check my last comment, please.

**Comment by zaibon** [comment]
@despiegk please have a look

**Comment by Dina-Abd-Elrahman** [comment]
## Jumpscale Version:

- core : 81301a84ddf956f36cfdedc0466fcac091ca6271
- lib : 79e15d574d0734ca5b0d8e27944416483720b5d3
- prefab : 44e92d0c9e47f663c1ede06e8d8c983905da581d

## 0-robot version : fad034d075c69a20aae170a83418692a2fc41642

## 0-templates version : b4efeead7bb1cc6d1c5033dc1fb67137e8c395b4 

## Verification steps: 

1- creating vm on zero-os node and install apache on it. 
2 - create Etcd container : 

-  data ={'nics': [{'type': 'default',                                                                                
            'id': 'None',
           'hwaddr': '',
           'name': 'nat0'}, {'type': 'zerotier','name':'zerotier', 'id': 'a09acf0233685d1f'}]}
- etcd = robot.services.find_or_create('github.com/threefoldtech/0-templates/etcd/0.0.1', 'test',data)
- etcd.schedule_action('install').wait(die=True)
- etcd.schedule_action('start').wait(die=True)

3- create Traefik container : 

- data ={'nics': [{'type': 'default',                                                  
           'id': 'None',
           'hwaddr': '',
           'name': 'nat0'}, {'type': 'zerotier','name':'zerotier', 'id': 'a09acf0233685d1f'}],'etcd':'test'}
- traefik=robot.services.find_or_create('github.com/threefoldtech/0-templates/traefik/0.0.1', 'test', data=data)
- traefik.schedule_action('install').wait(die=True)
- traefik.schedule_action('start').wait(die=True)

4- create CoreDns container :
 
- coredns=robot.services.find_or_create('github.com/threefoldtech/0-templates/coredns/0.0.1', 'test', data=data)
- coredns.schedule_action('install').wait(die=True)
- coredns.schedule_action('start').wait(die=True)

5- load keys and values on etcd:

- cl = j.clients.etcd.get('main', data={'host':'192.168.194.67','user':'root','password_':'wne2x8v70e'})
- cl.put('/hosts/ch/test/dina', '{"host":"10.102.104.231","ttl":60}')
- cl.put('/traefik/backends/backend1/servers/server1/url', 'http://192.168.194.7')
- cl.put('/traefik/frontends/frontend1/backend', 'backend1')
- cl.put('/traefik/frontends/frontend1/routes/frontend1/rule', 'Host:dina.test.ch')
