### ISSUE TITLE
0-templates can create ports from container or vm to the z-os node inspite these ports is reserved ones

### ISSUE THREAD

**Issue by hossnys** [threefoldtech/0-templates#132]
when you reserve a port using ```node_client.client.socat.reserve(1) ``` form client and then try to use the same port from another client to create a vm or container using 0-templates it'll create without looking if this port is reserved - used or not ,, so it's need to be fixed maybe by make creation take care only of container and vm ports and leave the z-os ports side for z-os to handle it , or make the creation check before in reserved ports pool to make sure that given ports in template is not reserved or used.

**Comment by zaibon** [comment]
```
Resever the given number of ports, and return the reserved ports

:note: A reserved port is not granteed to be used by u only, it means
other call to reserve for the next 2 minutes is granteed to not return
this port.

So to make reservation works properly, u first do `reserve` then use
the returned port for your forwards (u have 2 minutes). Once the port
forward is done, the port is never returned by reseve. If no port forward
was created using this port, the port is returned to the free pool

:note: port forward creation (using container, or kvm) doesn't check if the
port is reserved at all.
```

**Comment by hossnys** [comment]
> > when you reserve a port using node_client.client.socat.reserve(1) form client and then try to use the same port from another client to create a vm or container using 0-templates it'll create without looking if this port is reserved -
> 
> this is exactly the intended behavior, check the docstring:
> 
> ```
> Resever the given number of ports, and return the reserved ports
> 
> :note: A reserved port is not granteed to be used by u only, it means
> other call to reserve for the next 2 minutes is granteed to not return
> this port.
> 
> So to make reservation works properly, u first do `reserve` then use
> the returned port for your forwards (u have 2 minutes). Once the port
> forward is done, the port is never returned by reseve. If no port forward
> was created using this port, the port is returned to the free pool
> 
> :note: port forward creation (using container, or kvm) doesn't check if the
> port is reserved at all.
> ```

yes , i read this docstring before , but it needs to be handled  to avoid different services with same ports which will cause a mess

**Comment by zaibon** [comment]
It doesn't need anything. This is a primitive of zero-os. People implementing stuff on top needs to use it properly.
