### ISSUE TITLE
Adapt the VM template to use zero-os flist with kernel directly inside

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/0-templates#133]
At the moment the flist used to boot zero-os virtual machine only contains a generic ipxe script. So to boot a zero-os vm, we need to pass it an ipxe url, then the kernel is downloaded from the bootstrap service, all the files are downloaded and the vm finally boots. 

This is extremely inefficient cause we download all the same file again and again for each VM created.
Instead what we should do is having an flist that already contains the zero-os kernel. Like this we can use the shared cache feature like any other flist, this will make the VM to boot in no time since all the files are already local and nothing to download at boot anymore.

So for this task we need to adapt the `dm_vm` and `vm` tempate and the zos SAL to use this flist with the kernel directly inside.

In the `dm_vm` template here is the section that choose what kind of VM to boot:
https://github.com/threefoldtech/0-templates/blob/78a6394d8ed0e4921571136085b7fc860fb80f5f/templates/dm_vm/dm_vm.py#L114-L129
This is passed along in the `vm` template that pass it to the zos SAL which finally writes it in filesystem of the vm before deploying it:

```python
def deploy(self):
        if 'ipxescript' in self.configs:
            self.configs.remove('ipxescript')
        resp = requests.get(self.ipxe_url)
        resp.raise_for_status()
        self.configs.add('ipxescript', '/boot/ipxe-script', resp.content.decode('utf-8'))
super().deploy()
```

This use of ipxe url needs to be removed and instead we can pass the kernel arguments needed by zero-os (zerotier network, farmer_id, debug flags...) using the `cmdline` argument of the KVMManager class : 

https://github.com/threefoldtech/jumpscale_lib/blob/e7f8721a238e41e04854f5552be42144b957f256/JumpscaleLib/clients/zero_os_protocol/KvmManager.py#L197

**Comment by serboctor** [comment]
https://github.com/threefoldtech/0-templates/pull/140
https://github.com/threefoldtech/jumpscale_lib/pull/171

**Comment by zaibon** [comment]
verified
