### ISSUE TITLE
s3: deployment of a passive minio VM 

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/0-templates#149]
The passive minio VM is exactly the same as the active VM, the only difference is that in the passive minio configuration we need to specify the address of the tlog zdb active so it can do the replication of the metadata.

From a code perspective I'm not sure what's the best way how to approach this.
Probably we should re-shuffle services a bit so we can have a service that represent a full s3 then have a higher level service that is managing the active and passive s3 services. This would make our live easier in term of self-healing since we'll have to make a passive become active and things like that.

Something to take in account when deploying zdb namespaces of a passive s3 instance, is that is should as much as possible be on different nodes that the one used by the active. Otherwise in case of node offline, we loose both active and passive at the same time.

This all sounds like capacity planner (3bot) is the answer for this, but I'm waiting to see any working demo of it.

depends on :
- https://github.com/threefoldtech/0-templates/issues/148

**Comment by serboctor** [comment]
Create new service `s3_manager` to be responsible for creating the active and passive s3 services. 

schema:
```
struct Schema {
    mgmtNic @0: Nic; # zerotier management nic
    farmerIyoOrg  @1: Text; # the farmer to create the s3 on
    dataShards @2: Int32=16; # 0-stor data shards config
    parityShards @3: Int32=4; # 0-stor parity shards config
    storageType @4: StorageType; # s3 storage type
    storageSize @5: UInt64; # total s3 storage size in GB
    minioLogin @8: Text; # minio login
    minioPassword @9: Text; # minio passwor
    nsPassword @10: Text; # Namespace password
    minioBlockSize @12 :UInt32=1048576; # minio data block size in bytes

    enum StorageType {
     hdd @0;
     ssd @1;
    }

    struct Nic {
      id @0: Text; # Zerotier network id
      ztClient @1: Text;
    }
    }
```
`s3_manager` will first install the active s3, then use info about the nodes used by the active s3, to create the passive s3. While sorting the nodes to attempt installing namespaces on, the passive s3 will put those nodes at the end of the list to make it less likely that a namespace is installed on it.

**Comment by zaibon** [comment]
I would't call it s3_manager, cause this is the higher level service that client will use. So it needs to remain called s3. Which means we need to rename the service currently call s3 to something else.

**Comment by serboctor** [comment]
Settled with @zaibon on renaming `s3_manager` to `s3_redundant` and keeping the current `s3` as is.

**Comment by Pishoy** [comment]
@serboctor can you write the verification steps ?

**Comment by ramezsaeed** [comment]
As discussed with Chris an Sarah, they will review the whole logic again

**Comment by serboctor** [comment]
As discussed, I modified the s3_redundant to deploy the passive s3 with the same namespaces as the active s3. This task only includes the deployment of the s3s, it doesn't include any self-healing implementation. For self-healing we have other tasks.
When you install an s3_redundant, it will create two s3s, active and passive one. The passive one acts as a slave where you have read-only access to the data.

**Comment by Pishoy** [comment]
verified 
```In [14]: data = {
    ...:     'farmerIyoOrg': 'kristof-farm',
    ...:     'mgmtNic': {'id':'35c192ce9b7015e9', 'ztClient': 'main'},
    ...:     'storageType': 'hdd',
    ...:     'dataShards':4, 
    ...:     'parityShards': 1,
    ...:     'storageSize': 500,
    ...:     'minioLogin': 'login',
    ...:     'minioPassword': 'password',
    ...: }


In [20]: s3_redundant = robot.services.create('github.com/threefoldtech/0-templates/s3_redundant/0.0.1','s3Redun', data)

In [21]: s3_redundant.schedule_action('install').wait(die=True)
Out[21]: install

In [22]: s3_redundant.schedule_action('urls').wait(die=True)
Out[22]: urls

In [23]: _.result
Out[23]: 
{'active_urls': {'public': 'http://172.26.131.96:1024',
  'storage': 'http://10.102.141.236:1028'},
 'passive_urls': {'public': 'http://172.26.7.110:1024',
  'storage': 'http://10.102.141.236:1030'}}

In [24]: s3_redundant.schedule_action('stop_active').wait(die=True)
Out[24]: stop_active

In [25]: s3_redundant.schedule_action('start_active').wait(die=True)
Out[25]: start_active

```
- js version 
```
root@e7605ba47d5c:/opt/code/github/threefoldtech/0-templates# git log -1
commit 4c752681b84a8edfe9aeca09a8f7471a47f9b5e5
Author: serboctor <boctor.sarah@gmail.com>
Date:   Wed Oct 31 13:11:55 2018 +0200

    Fix state check in etcd
```
