### ISSUE TITLE
s3: handling data disk failures

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/0-templates#152]
minio template needs to watch the logs from minio process and in the cases where it see minio cannot access some shards or some IO error happens, the robot needs to take actions.

Example flow:

- Minio output some logs showing it cannot reach some shards (https://github.com/threefoldtech/minio/issues/16)
- minio template see these logs
- minio template update it's state to be marked as unhealthy
- s3 template detect minio state is unhealthy 
- we need to find a way for minio and s3 template to exchange the information about which shards is  unreachable (TODO)
- s3 template checks the zdb namespace states
  -  if it can just restart it -> restart it
  - if disk is really dead, reserve a new namespace on a new disk -> update minio configration with new shards -> minio service send signal to minio process to ask to reload its config -> ask minio to start healing proces to write missing data on the new shards
  
To whoever takes this task, you migh needs to open some issue on [minio repo](https://github.com/threefoldtech/minio) to have all the feature you need in order to complete this task

**Comment by zaibon** [comment]
>we need to find a way for minio and s3 template to exchange the information about which shards is unreachable (TODO)

regarding this, we are going to use the state of the minio service to share information about which shard is unhealthy.
Example:
```python
#minio state
{'data_shards' : 
   {'192.168.4.12:1450': 'ERROR'},
   {'192.168.4.16:1450': 'OK'},
   {'192.168.4.20:1455': 'ERROR'}
'tlog_shards : 
   {'192.168.4.10:1500: 'OK'}
}
```
Then the s3 service will watch minio state and trigger self-healing accordingly

**Comment by Dinaamagdy** [comment]
https://github.com/threefoldtech/minio/blob/datashards_failure/test/failures_testsuite/testcases/s3_redundant/test04_minio_active_passive.py#L349
