### ISSUE TITLE
 s3: handling tlog disk failures for passive minio

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/0-templates#154]
minio template needs to watch the logs from minio process and in the cases where it see minio cannot access or some IO error happens on the tlog zdb namespace.

Example flow:
- Minio output some logs showing it cannot reach the tlog shard
- minio template see these logs
- minio template update it's state to be marked as unhealthy
- s3 template detect minio state is unhealthy 
- we need to find a way for minio and s3 template to exchange the information about which shards is  unreachable (TODO)
- s3 template checks the zdb namespace states
  -  if it can just restart it -> restart it
  - if disk is really dead
    - reserve a new namespace on a new disk
    - update minio configration with new tlog shard
    - minio service send signal to minio process to ask to reload its config
    - minio process will then start replicating new metadata from the active minio on the new tlog shard

  
To whoever takes this task, you migh needs to open some issue on [minio repo](https://github.com/threefoldtech/minio) to have all the feature you need in order to complete this task

**Comment by Pishoy** [comment]
verified 
```
In [10]: s3_redundant.schedule_action('urls').wait(die=True)
Out[10]: urls

In [11]: _.result
Out[11]: 
{'active_urls': {'public': 'http://172.26.215.158:1024',
  'storage': 'http://10.102.96.237:1055'},
 'passive_urls': {'public': 'http://172.26.118.140:1024',
  'storage': 'http://10.102.96.237:1057'}}
```
- passive minio data yaml file 
```
tlog:
    address: 10.102.115.21:1039
    name: beb7b449-391d-4af8-b60d-b50997306b8c
    node: ac1f6b272370
    url: http://10.102.115.21:6600
```
- kill the tlog of passive minio 
```
In [17]: tcl = j.clients.zos.get_by_id('ac1f6b272370')

In [18]: zrobot = tcl.containers.get('zrobot')

In [19]: zrobot.client.bash('zrobot godtoken get ').get()
Out[19]: 
STATE: 0 SUCCESS
STDOUT:
god token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdXRoZW50aWNhdGlvbiI6ImdvZF90b2tlbiJ9.9dIqwzu_awTBYB2CIsVQOa-gaI5DnvwFGB78DIQqz-s 

STDERR:

DATA:


In [20]: remote = j.clients.zrobot.new('test',data={'url':'http://10.102.115.21:6600','god_token_':'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdXRoZW50aWNhdGlvbiI6ImdvZF90b2tlbiJ9.9dIqwzu_awTBYB2CIsVQOa-gaI
    ...: 5DnvwFGB78DIQqz-s'})

In [21]: trobot = j.clients.zrobot.robots.get('test')

In [22]: tservice = trobot.services.get(name='beb7b449-391d-4af8-b60d-b50997306b8c')

In [23]: tservice.schedule_action('uninstall')
Out[23]: uninstall
```
- check the namespace was already deleted
```
pishoy@pishoy-laptop:~$ redis-cli -h 10.102.115.21 -p 1039
10.102.115.21:1039> nslist
1) "default"
```

- check passive minio , got return back after a while with the same data on active minio 

- 0-template version
