### ISSUE TITLE
s3: active/passive minio management

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/0-templates#155]
In case the active of the passive minio VM dies, the robot needs to act to get back to an healthy situation.

Case where the passive VM dies:
- Redeploy a new VM and configure it to be the passive one replicating from the active

Case where the active VM dies:
- The reverse proxy stops serving requests to the broken minio VM
- Update configuration of the passive minio to become the active one
- The reverse proxy starts forwarding requests to the passive minio VM which as becomes the active minio
- Deploy a new minio VM and configure it to be the passive one, replicting metadata from the newly active

**Comment by serboctor** [comment]
For verification, please also check https://github.com/threefoldtech/0-templates/issues/197 to understand how the reverse_proxy is created. To test the whole solution, you'll need to have a web_gateway and a reverse_proxy service created too.

**Comment by ramezsaeed** [comment]
steps to verify


- Create a web_gateway service
- Create a reverse proxy service that points to this web_gateway. At this point it wont have any servers.
- Install s3_redundant.
- Execute action update_reverse_proxy which takes argument reverse_proxy on s3_redundant to update it witht the reverse proxy service name this action will also update etcd with the backend url being the active url.
- Cause a failure that would cause a promotion to happen
- After the self healing is done, check again etcd, it should now point to the new active s3.

This is the key you should check on etcd /traefik/backends/<reverse_proxy_name>/servers/server0/url

**Comment by zaibon** [comment]
![photo_2018-08-23_09-46-25](https://user-images.githubusercontent.com/303164/49240573-c7dd8f00-f405-11e8-9c25-63cbd9f87ada.jpg)

verified

**Comment by Pishoy** [comment]
- steps to create a webgetway and reverse proxy 
https://gist.github.com/Pishoy/06fa1a58cb6b7296a1e61f2956e1d088
- etcd verification
```

In [108]: s3_redundant.schedule_action('update_reverse_proxy', args={'reverse_proxy': rp.name})
Out[108]: update_reverse_proxy

In [109]: _.wait(die=True)
Out[109]: update_reverse_proxy

In [127]: cl = j.clients.etcd.get('test', data={'host':'192.168.196.91', 'password_':'aj1adnidsms8ph60', 'user':'root'})

In [129]: cl.api.get('/traefik/backends/rp/servers/server0/url')
     ...: 
Out[129]: (b'http://10.102.115.21:1057', <etcd3.client.KVMetadata at 0x7f302c9054e0>)
In [130]: s3_redundant.schedule_action('urls').wait(die=True).result
Out[130]: 
{'active_urls': {'public': 'http://192.168.196.31:1024',
  'storage': 'http://10.102.115.21:1057'},
 'passive_urls': {'public': 'http://192.168.196.220:1024',
  'storage': 'http://10.102.113.188:1053'}}

In [131]: s3_redundant.schedule_action('_promote').wait(die=True).result

In [132]: s3_redundant.schedule_action('urls').wait(die=True).result
Out[132]: 
{'active_urls': {'public': 'http://192.168.196.220:1024',
  'storage': 'http://10.102.113.188:1053'},
 'passive_urls': {'public': 'http://192.168.196.71:1024',
  'storage': 'http://10.102.133.88:1030'}}

In [134]: etcd = j.clients.etcd.get('test', data={'host':'192.168.196.91', 'password_':'aj1adnidsms8ph60', 'user':'root'})
In [136]: etcd.api.get('/traefik/backends/rp/servers/server0/url')
Out[136]: (b'http://10.102.113.188:1053', <etcd3.client.KVMetadata at 0x7f302c8f1320>)
```
- 0-tempaltes 
```
commit 6a4ddb28c3ebe66dfe0558cef1e98374c1e0282d
Author: Christophe de Carvalho Pereira Martins <christophe.dcpm@gmail.com>
Date:   Thu Nov 29 18:00:42 2018 +0100

    don't destroy the schema format by wiping with a None value
```
