### ISSUE TITLE
change the default memory value on dm_vm template 

### ISSUE THREAD

**Issue by Pishoy** [threefoldtech/0-templates#158]
- i have tried to create a ubuntu/zos VM using dm_vm template, if i did not put the memory value on vm data , the vm booting is fail due to the default value of memory is 128 which not acceptable to start the vm 

- the Ubuntu vm booting works if i set the memory to 256M  
- the zos vm booting works if i set the memory to 1024M , the zos vm can not boot if i put memory ( 128,256,512)

-  i suggest to modify the default value in template to be 256 in case Ubuntu vm and 1024 M in case zos vm 
- the error is attached when the booting fail 
![fail](https://user-images.githubusercontent.com/21987477/46681123-d8823d80-cbea-11e8-9b31-2b7be8fb46de.jpg)

- node zos version 
```
In [107]: node_client.ping
Out[107]: <bound method Node.ping of Node <10.102.234.229:6379>>

In [108]: node_client.ping()
Out[108]: 'PONG Version: development @Revision: 90e5e4e9aa8bc62cc0729cb6d5e348b64adcae93'
```
- zrobot 0-tempaltes repo is development branch

**Comment by serboctor** [comment]
We can't define two default, and if we change it based on the image then we might change a value that the user added without knowing. I think it should be the user's responsibility to create a service with appropriate values. I can add info in the docs stating that the 0-os vm requires a minimum of x. Or may be raise a validation error if the memory is too low. @zaibon do you have another opinion?

**Comment by zaibon** [comment]
>  think it should be the user's responsibility to create a service with appropriate values.

indeed. But on the other hand, 128MiB is also ridiculously small. We should have a proper number, 1GiB seems about right.

More documentation is always good. So yes improving that should help too. We should even maybe add a feature to the hub so we can attach dos to the flist to communicate these kind of stuff. (cc @maxux )

Regarding raising an error in validation, I'm not sure. 128 is a valid value but just not for any flist.

**Comment by serboctor** [comment]
https://github.com/threefoldtech/0-templates/commit/a7f95b767024923add81cb3feaa6c23c9c2b4f4a

**Comment by zaibon** [comment]
@Pishoy don't forget to close this one when verified

**Comment by Pishoy** [comment]
verified 
default value is 1024 M on both zos and Ubuntu VMs 

```
In [14]: node_client.client.kvm.list()
Out[14]: 
[{'default_ip': '172.19.0.12',
  'id': 11,
  'ifctargets': ['tap0'],
  'name': 'e93b0a06-ec12-4330-aa10-097ac7f3d08c_vm',
  'params': {'cmdline': 'zerotier=1c33c1ced064fefe ztid=9f2b2961d3:0:3a2aeab1c8556ce535a013a581841963428f25d362c2db9ef441edaacfd3cf6636ae0234fd64786484427e3892ca8b53cd66cde99e9af1042a93d62bf80a00d4:4cd1c141b0a857dda5888a881084759f80f010e111760cda1ced439f2214289e51c2bb4e34b26ec21bca2bdef06d9f16910a7b99d954e2ee718e9bc487a34857',
   'config': {'/etc/fstab': 'root / 9p rw,cache=loose,trans=virtio 0 0\nLABEL=test /mnt btrfs defaults 0 0\n',
    '/etc/systemd/system/multi-user.target.wants/zt-1c33c1ced064fefe.service': '[Unit]\nDescription=ZT Network Join\nAfter=zerotier-one.service\n\n[Service]\nExecStart=/usr/sbin/zerotier-cli join 1c33c1ced064fefe\nRestartSec=5\nRestart=on-failure\nType=simple\n',
    '/root/.ssh/authorized_keys': 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8o0jEGYqe2k7J0TNL6Gg8h86ic3ReiC6THlBnOKPDiKProj/4uMTmi1Qf5OcLIdeHgcP+zy+ZL4kpP7N6VTALRPiTn6Lty6ZP+5mQocaJYosoGLzB6+lx1NW/zXtscv4V3goULiDEx9SBzSuD8wS0k00iHcRjmuFUIfERyYR8mjmWC/sRf1Y7qk9kQjFOLW5Sw0+RLrxr4l2ur/n8bDVgGVpzWypKIsqRU6Rf1HdXWmdAMCucPAkxR5WNies5QFOkyllxI6Fq+G9M0Uf+EubpfpC1oOMWjNFy781M4KZF+FXODcBlwevfvk0HH/5mTHOymIfwVV8vjRzycxjuQib3 pishoy@Bishoy-laptop',
    '/var/lib/zerotier-one/identity.public': '9f2b2961d3:0:3a2aeab1c8556ce535a013a581841963428f25d362c2db9ef441edaacfd3cf6636ae0234fd64786484427e3892ca8b53cd66cde99e9af1042a93d62bf80a00d4',
    '/var/lib/zerotier-one/identity.secret': '9f2b2961d3:0:3a2aeab1c8556ce535a013a581841963428f25d362c2db9ef441edaacfd3cf6636ae0234fd64786484427e3892ca8b53cd66cde99e9af1042a93d62bf80a00d4:4cd1c141b0a857dda5888a881084759f80f010e111760cda1ced439f2214289e51c2bb4e34b26ec21bca2bdef06d9f16910a7b99d954e2ee718e9bc487a34857'},
   'cpu': 1,
   'flist': 'https://hub.grid.tf/tf-autobuilder/zero-os-development.flist',
   'media': [{'bus': '',
     'type': 'disk',
     'url': 'zdb://172.18.0.30:9900?size=5G&blocksize=4096&namespace=u31qu6st07&password=2ayhvcqzpcn8rbvzd4lc9zq830o4ejeb'}],
   'memory': 1024,
   'mount': [],
   'name': 'e93b0a06-ec12-4330-aa10-097ac7f3d08c_vm',
   'nics': [{'hwaddr': '00:28:06:82:00:0c', 'id': 'None', 'type': 'default'}],
   'port': {},
   'share_cache': True,
   'storage': '',
   'tags': []},
  'state': 'running',
  'tags': [],
  'uuid': 'c2871f25-a1f3-4314-bb68-8a3a0d91ff6f',
  'vnc': 5900}]

```
-  0-tempales version 
```
commit a7f95b767024923add81cb3feaa6c23c9c2b4f4a
Author: serboctor <boctor.sarah@gmail.com>
Date:   Wed Oct 10 11:05:23 2018 +0200

    Change default memory size for dm_vm template
```
```
