### ISSUE TITLE
CoreDNS template and the standard RFC world

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/0-templates#178]
## Concept

To have a coredns running as an authoritative nameserver for your (sub) domain, you need a sane SOA record, as many registrars do sanity checks to your nameservers before updating their records to point to the Coredns nameservers.

For that, you'll need to create  a proper zonefile, as the etcd part for coredns does NOT include proper adding zones and their authoritative section.

Luckily, coredns can automatically load the zoenfiles you put in place, so it's just creating the file that is needed.
## Make it

What's needed:

  - knowledge of your domain(s)  (e.g. cloudrobot.org, or threefold.cloudrobot.org)
  - 2 ip address that have a coredns listener.
  - a Corefile template 
  - a zonefile template per zone that coredns will be authoritative for

### Files : 

  - Corefile

```
. {
    log
    errors
    forward .  8.8.8.8 1.1.1.1
    etcd {
        stubzones
        fallthrough
        path /hosts
        endpoint http://localhost:2379
    }
    auto . {
        directory /etc/coredns/zones db\.(.*) {1} 10 
    }
}


```
(note: there are no domains to handle in that Corefile)

  - zonefiles

we maintain a zone directory where we put a `db.zone` per zone we are going to serve (e.g. `/etc/coredns/zones/db.threefold.cloudrobot.org`)

`/etc/coredns/zones/db.{{zone}}`

```
$TTL    604800
@    IN    SOA    ns1.{{zone}}. admin.{{zone}}. (
                  5        ; Serial
             604800        ; Refresh
              86400        ; Retry
            2419200        ; Expire
             604800 )    ; Negative Cache TTL
;

@    IN    NS    ns1
@    IN    NS    ns2


ns1     IN      A       {{IP1}}
ns2     IN      A       {{IP2}}

```
where : 
  - zone = your (sub)domain
  - IP1   = ip address of first coredns server
  - IP2   = ip address of second coredns server

**Comment by zaibon** [comment]
Ok so this change a bit how we've designed the coredns template. So things I can alreaady see that needs to be changed:

- coredns template will have to provide action to create new zone. Since we cannot just push the zone configuration into etcd, we have to let the coredns template create files in the container itself.
- the webgateway concept will requires 2 coredns instead of 1

**Comment by zaibon** [comment]
@delandtj can you check if this code already does what we need please: https://github.com/threefoldtech/jumpscale_lib/tree/development_simple/JumpscaleLib/clients/coredns

**Comment by BolaNasr** [comment]
@zaibon  @delandtj  i'm working on it and i changed in structure , i will commit my changes today

**Comment by BolaNasr** [comment]
PR: https://github.com/threefoldtech/jumpscale_lib/pull/215
