### ISSUE TITLE
s3: handling tlog service dying forever 

### ISSUE THREAD

**Issue by 0xIslamTaha** [threefoldtech/0-templates#186]
https://github.com/threefoldtech/home/issues/22#issuecomment-422867737

To simulate the metadata dies forever scenario I did the following steps:
```
- upload a file
- delete tlog namespace service
- delete tlog zdb service 
- kill zdb container
- download the file, passed 
- Try to uplaod antoehr file » failed with "Namespace not found error "
```

and the minio is no corrupted as there is no tlog service. After discussion with @zaibon, we figured out that the expected scenario is 
```
If we found out we don't have the service anymore, we'll have to create a new one
to get the system back on track
```

**Comment by serboctor** [comment]
I discussed this with @zaibon and we agreed it is not really realistic that a service would get deleted. However, I refactored the namespace monitoring, and now if a zerodb is not running anymore and failed to restart for any reason, the namespace service will reinstall itself on another zerodb.
https://github.com/threefoldtech/0-templates/pull/209

**Comment by 0xIslamTaha** [comment]
after stopping the tlog service, the monitoring create the namespace in a new zdb as I can see but I can't upload a file and the minio returns '(too many?) shards are unavailable' 

**re-produce script**
```python
s3 = demo.s3['s3_demo_5']
tlog = s3.service.data['data']['tlog']
robot = j.clients.zrobot.robots[tlog['node']]
robot._try_god_token()

ns = robot.services.get(name=tlog['name'])
print(ns.name)

zdb = robot.services.get(name=ns.data['data']['zerodb'])
print(zdb.name)

zdb.schedule_action('stop').wait(die=True)
zdb.schedule_action('start').wait(die=True)

new_zdb = robot.services.get(name=ns.data['data']['zerodb'])
print(new_zdb.name)
```

Try to upload file now

**Comment by 0xIslamTaha** [comment]
self healing is only work for the s3_redundant and there is nothing to do here
