### ISSUE TITLE
explorer config file doesn't have support for access controll headers

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/0-templates#20]
This means that cross domain js requests are not possible, while it is definitely desired. For instance the threefold app requires this to function correctly. Example of a caddy file which supports this can be found here: https://github.com/threefoldfoundation/tfchain/blob/master/frontend/explorer/caddy/Caddyfile

**Comment by lucasvanhalst** [comment]
When can this be added? It's needed for the app and else requests to the explorers won't work @zaibon

**Comment by zaibon** [comment]
This is already changed in jumpscale. But we need to wait for jumpscale to release so we can integrate this into the 0-robot flist.
Release of 9.3.0 is planned for sunday
