### ISSUE TITLE
node_port_manager assigns a port to a service even though it is assigned to another service

### ISSUE THREAD

**Issue by serboctor** [threefoldtech/0-templates#214]
I created a namespace, which in turn creates a zerodb. This zerodb was assigned port 1024.
I stopped this zerodb, and made sure the monitoring wont start it again.
The namespace monitoring reinstall the namespace on a another zerodb, which in turn creates another zerodb. The second zerodb was assigned the same port as the first zerodb.
And this is how the data of the node_port_manager looks like:
```ports:
-   port: 1024
    serviceGuid: f5c78d8a-19ef-453a-b65d-40d376153956
-   port: 1024
    serviceGuid: 04d67658-f244-40cd-bb2a-21a907416fec
```

Even though the first zerodb service was stopped, its port shouldnt have been assigned to the second zerodb service because it is still reserved by the first zerodb service.

**Comment by serboctor** [comment]
Fixed by https://github.com/threefoldtech/0-templates/commit/46f5abee03e53880096f9aa6f57668b6ff6a1cd3

**Comment by hossnys** [comment]
verified: 
0-templates : 8b0758d
Js9_core : 74c2b1f
