### ISSUE TITLE
set `timeout` for all wait(die=True) calls

### ISSUE THREAD

**Issue by 0xIslamTaha** [threefoldtech/0-templates#216]
**Description**
As I can see we call `wait(die=True)` lots of time in all templates specially s3 and s3_redundant and in some cases, the action is hanging forever cause it uses `die=True` without any timeout conditions. I suggest setting `timeout=BIG_VALUE` to make sure that we r not hanging forever.

**Comment by serboctor** [comment]
@zaibon wouldnt it make more sense to add an appropriate default timeout in 0-robot and only increase/decrease it in certain actions whenever needed?

**Comment by zaibon** [comment]
yeah but the problem is what is an appropriate timeout ?
Cause we have action that can take 1s like 15 minutes.
but yeah we should have a default timeout so we never get stuck forever

**Comment by zaibon** [comment]
Since https://github.com/threefoldtech/0-robot/issues/51 task can be canceled when someone is waiting on them with a timeout. That can prevent any dead lock
