### ISSUE TITLE
Causing ssd failure to the tlog ssd  of the minio vm, doesn't trigger another vm installation

### ISSUE THREAD

**Issue by john-kheir** [threefoldtech/0-templates#220]
## Scenario
1- Cause failure to the vdisk ssd of the minio vm
2- Try to create a bucket on this minio

## Actual Results 
1- zerodb, vdisk, vm services are still okay and running which should be expected 
2- checking minio logs
```
[2018-11-14T15:34:15.786614138Z] [ERROR] Unexpected error, please report this issue at https://github.com/minio/minio/issues (Internal Error (data))
time="2018-11-14T15:35:34Z" level=info msg=StorageInfo
time="2018-11-14T15:35:40Z" level=info msg="MakeBucketWithLocation bucket=test, location=\n"
{"error":"Internal Error (data)","level":"error","master":false,"msg":"failed to write transaction log","namespace":"namespace_tlog","time":"2018-11-14T15:35:40Z","tlog":"10.102.234.243:1064"}

```

**Comment by muhamadazmy** [comment]
From the log message above, I found out that the minio actually failed on writing the tlog record (as the message exactly states) so it **never** reached the place where it writes to the actual vm disk.

It means:
- The wrong zdb with corrupted 
- Both tlog and vm disk are sharing the same instance of zdb (can u confirm that)

Anyway, i will add code necessary to produce the correct log message to kick start repair.

**Comment by ramezsaeed** [comment]
@john-kheir 
the loop happened again .. but this time the vdisk used different ssd from the tlog

https://gist.github.com/john-kheir/52bb31a2ecf01e1bf79933f707ff19b8

**Comment by ramezsaeed** [comment]
@john-kheir 

- after installing s3_red we make sure that active/passive Tlog/Vdisk are on 4 different SSDs
- corrupted the Tlog SSd for The active using echo 1 > /sys/block/sdf1/device/delete
- The passive had been promoted successfully to be the new Active, and we can upload and download the old files too.
- the failed active had been redeployed and added in the service data as passive now.
-- BUT no replication is happening and the new passive is just and empty minio, cannot see the previously uploaded files nor the new uploaded ones.


@muhamadazmy 
for how long should we wait till the full replication done to the new passive ?

**Comment by ramezsaeed** [comment]
Working OK with active and passive VMs now
