### ISSUE TITLE
Creating gateway with portforward, result target port same as source port in container info

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/0-templates#226]
```
data={'hostname': 'b54e7f898708eeb7428a08', 'networks': [{'name': 'nat0', 'type': 'default', 'public': True, 'id': ''}, {'name': 'zerotier_nic', 'type': 'zerotier', 'id': '1d719394048f3525', 'ztClient': 'c3477dac9423a9cb64e8cb', 'public': False}], 'portforwards': [{'protocols': ['tcp'], 'srcport': 3568, 'srcnetwork': 'nat0', 'dstip': '10.147.18.114', 'dstport': 2801, 'name': 'myport'}, {'protocols': ['tcp'], 'srcport': 6000, 'srcnetwork': 'nat0', 'dstip': '10.147.18.114', 'dstport': 5000, 'name': 'portt'}], 'httpproxies': [], 'domain': '', 'certificates': [], 'routes': [], 'ztIdentity': ''}
```
### steps:
1- create gateway with this data using (template: github.com/threefoldtech/0-templates/gateway/0.0.1)
2- get gateway's container info

### Actual Result
The target port is same as source port in container info
port forward from public network to private one (did it twice on these ports 6000, 3568 to make sure)

![image](https://user-images.githubusercontent.com/41957921/48771977-a96fe900-eccb-11e8-9d81-988bf5d0ac0f.png)

**Comment by muhamadazmy** [comment]
Clearing a miss-understanding on the gateway port-forwards

- with ZOS port forward you can NOT specify a destination address, it's always the VM or Container private address (default network)
- Gateway does a trick by first forward the required ports to the gateway internal ports (same as source port), then internally it maintain it's own firewall rules to re forward those ports to the required destination ip:port

So from what I see, this looks correct. To validate, run `nft list ruleset` inside the container to check that those ports are reforwarded to the requested destination.

@grimpy  please confirm

**Comment by AhmedHanafy725** [comment]
Yes, I found the rule inside the container.
![image](https://user-images.githubusercontent.com/41957921/48906361-e0313500-ee6c-11e8-95b1-245d3d85a7f5.png)
and this rule in the node
![image](https://user-images.githubusercontent.com/41957921/48906497-461dbc80-ee6d-11e8-8fd7-79d1fc434510.png)
and I had a server running on`10.147.18.196:2856`
so I was expecting to reach the server through`10.2.20.4:3176`, but this didn't happen
