### ISSUE TITLE
'This name is not allowed' error on zdb backend

### ISSUE THREAD

**Issue by chrisvdg** [threefoldtech/0-templates#230]
Setting the zdb backend fails as seen on the below screenshot

![image](https://user-images.githubusercontent.com/23582741/48777517-0ae78600-ecd3-11e8-9b6b-f91e088da035.png)

Provided `dataRepo` for the `zrobot_config` is `zdb://man-dc01.gig.tech:9900/MAN-DC01-F0805-ARC02/ac1f6b457c78` in which the namespace `ac1f6b457c78` is the machine id of the host the robot is running on.

Using `redis-cli` creating this namespace works just fine
![image](https://user-images.githubusercontent.com/23582741/48777632-67e33c00-ecd3-11e8-9b3c-8b377e2cef89.png)

My guess is that the issue may be coming from the zdb client

**Comment by 0xIslamTaha** [comment]
![image](https://user-images.githubusercontent.com/17981089/48778235-4b4c0180-ecdd-11e8-83c4-dedfb719a225.png)
so MAN-DC01-F0805-ARC02/ac1f6b457c78 this is invalid name

**Comment by chrisvdg** [comment]
Yep, provided a namespace into my script parameters while the script adds the namespace itself!
