### ISSUE TITLE
installing s3 got stuck cause of failed to create a vdisk on a node

### ISSUE THREAD

**Issue by 0xIslamTaha** [threefoldtech/0-templates#237]
I have been trying to create a single s3 in banchadati env, then It got stuck forever. After digging I found that the minio VM has not been installed cause of it failed to create its Vdisk. I checked the node and I found that The node service can't create a new zdb for this vdisk.

node : ac1f6b457b6c

**Comment by serboctor** [comment]
Installation works fine now and doesn't block
