### ISSUE TITLE
after uninstalling bridge, it would come back again

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/0-templates#260]
`bridge_data = {'name': 'test_bridge', 'hwaddr': None, 'mode': 'static', 'nat': False, 'settings': {'cidr': '10.20.30.1/24'}}`

### Steps:
1- create bridge with this data using (template: github.com/threefoldtech/0-templates/bridge/0.0.1)
2- install the bridge
3- uninstall the bridge 

### Actual Result: 
Checking the bridge list `node.client.bridge.list()`, won't be found.
Waiting for 30 sec and check again, will be found.

**Comment by AhmedHanafy725** [comment]
![image](https://user-images.githubusercontent.com/41957921/49339739-cd71e980-f63e-11e8-8c4d-3315459f65b3.png)

**Comment by serboctor** [comment]
@muhamadazmy  the template basically just executes `client.bridge.delete(bridge)` so I assume this is a 0-core bug?
