### ISSUE TITLE
backplane healthcheck gives false positives

### ISSUE THREAD

**Issue by chrisvdg** [threefoldtech/0-templates#264]
For Bancadati I'm getting a alert for most nodes that the backplane interface is down

![image](https://user-images.githubusercontent.com/23582741/49371334-6d8b4980-f6f7-11e8-8d59-70c6c5f0825c.png)

When checking the interfaces, all seem to be UP (enp2s0f0, enp2s0f1 and backplane)
![image](https://user-images.githubusercontent.com/23582741/49371412-a9261380-f6f7-11e8-82b1-69a3147f9b1b.png)

Pinging in the storage network works
![image](https://user-images.githubusercontent.com/23582741/49371476-d8d51b80-f6f7-11e8-980a-e27b2aaa63c3.png)

Full alert
![image](https://user-images.githubusercontent.com/23582741/49371547-1a65c680-f6f8-11e8-907c-cc6acfc1cd53.png)

**Comment by zaibon** [comment]
https://github.com/threefoldtech/0-templates/commit/d53a77e7cd0d880b70964245ac061e94455d5c6b
