### ISSUE TITLE
Testcases for node_port_manager template

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/0-templates#282]
template: [node_port_manager](https://github.com/threefoldtech/0-templates/tree/development/templates/node_port_manager)
- Add test cases to cover node_port_manager template.

**Comment by hossnys** [comment]
- Here is the tests [file](https://github.com/threefoldtech/0-templates/blob/development_960/tests/testcases/a_basics/node_port_manager_testcases.py)
