### ISSUE TITLE
Issue in reverse proxy template

### ISSUE THREAD

**Issue by PeterNashaat** [threefoldtech/0-templates#300]
- had to comment that line to make it to work [link](https://github.com/threefoldtech/0-templates/blob/development/templates/reverse_proxy/reverse_proxy.py#L27)
- getting this error when i try to create a [reverse_proxy](https://github.com/threefoldtech/0-templates/tree/development/templates/reverse_proxy)

![reverse_proxy](https://user-images.githubusercontent.com/13523434/53020876-92729b80-3460-11e9-878c-585291b1b9eb.jpg)

**Comment by zaibon** [comment]
It is not a bug and removing this line breaks the template.
During the install we do a state check on the web_gateway service, see if it's actually running. 
Seems in your case it was not. So there were something wrong with the web_gateway itself
check https://github.com/threefoldtech/0-templates/blob/development/templates/web_gateway/web_gateway.py#L33
To see what are the condition to have a state running for the web_gateway
