### ISSUE TITLE
Development heartbeats (Send beats every 10 seconds)

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/0-templates#50]
*Issue migrated from [https://api.github.com/repos/zero-os/0-templates/issues/164](), opened by @xmonader*

For #https://github.com/Jumpscale/lib9/issues/298

We send a beat every 10 seconds using the capacity (send_beat)

**Comment by rkhamis** [comment]
*commented by @codecov-io
# [Codecov](https://codecov.io/gh/zero-os/0-templates/pull/164?src=pr&el=h1) Report
> Merging [#164](https://codecov.io/gh/zero-os/0-templates/pull/164?src=pr&el=desc) into [development](https://codecov.io/gh/zero-os/0-templates/commit/c7c862e2965ea2665f9c675e8e3654fcdf31e0b9?src=pr&el=desc) will **decrease** coverage by `<1%`.
> The diff coverage is `40%`.

[![Impacted file tree graph](https://codecov.io/gh/zero-os/0-templates/pull/164/graphs/tree.svg?height=150&width=650&token=FnorH2GFVB&src=pr)](https://codecov.io/gh/zero-os/0-templates/pull/164?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##           development   #164   +/-   ##
==========================================
- Coverage           92%    92%   -1%     
==========================================
  Files               32     32           
  Lines             3397   3402    +5     
==========================================
+ Hits              3132   3134    +2     
- Misses             265    268    +3
```


| [Impacted Files](https://codecov.io/gh/zero-os/0-templates/pull/164?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [templates/node/node.py](https://codecov.io/gh/zero-os/0-templates/pull/164/diff?src=pr&el=tree#diff-dGVtcGxhdGVzL25vZGUvbm9kZS5weQ==) | `61% <40%> (-1%)` | :arrow_down: |

------

[Continue to review full report at Codecov](https://codecov.io/gh/zero-os/0-templates/pull/164?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/zero-os/0-templates/pull/164?src=pr&el=footer). Last update [c7c862e...edd062e](https://codecov.io/gh/zero-os/0-templates/pull/164?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).
*

**Comment by zaibon** [comment]
not needed anymore
