### ISSUE TITLE
VM: default root password need to be randomize when we install a vm

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/0-templates#52]
*Issue migrated from [https://api.github.com/repos/zero-os/0-templates/issues/160](), opened by @zaibon*

Currently all the vm created from our flist images have the same root password. We want to improve this and generate a random password the first time the vm is installed.

**Comment by rkhamis** [comment]
*commented by @maxux
We need to use `chpasswd` tool with `--root` argument, and edit the root filesystem before it start, when starting from a flist. Like we do for ssh-keys.

This allows you to know the password (because we set it ourself) and it's lightweight.

The busybox version of `chpasswd` donesn't support `--root` argument, the real version from `shadow-utils` will be required.

Command to be executed is: `echo root:thepassword | chpasswd --root /path/flist/root`

I think it's the cleaner way to do it, what do you think @grimpy @delandtj ?*

**Comment by zaibon** [comment]
For now we've made the VM flist to have a random root password that no-one knows, So it is secure by default but the user have to pass it's public key to the VM during installation to be able to SSH the VM
