### ISSUE TITLE
Adds flist arg to zrobot upgrade

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/0-templates#53]
*Issue migrated from [https://api.github.com/repos/zero-os/0-templates/issues/155](), opened by @chrisvdg*

**Comment by rkhamis** [comment]
*commented by @codecov-io
# [Codecov](https://codecov.io/gh/zero-os/0-templates/pull/155?src=pr&el=h1) Report
> :exclamation: No coverage uploaded for pull request base (`master@c30a7dc`). [Click here to learn what that means](https://docs.codecov.io/docs/error-reference#section-missing-base-commit).
> The diff coverage is `16%`.

[![Impacted file tree graph](https://codecov.io/gh/zero-os/0-templates/pull/155/graphs/tree.svg?token=FnorH2GFVB&width=650&height=150&src=pr)](https://codecov.io/gh/zero-os/0-templates/pull/155?src=pr&el=tree)

```diff
@@           Coverage Diff           @@
##             master   #155   +/-   ##
=======================================
  Coverage          ?    92%           
=======================================
  Files             ?     32           
  Lines             ?   3307           
  Branches          ?      0           
=======================================
  Hits              ?   3072           
  Misses            ?    235           
  Partials          ?      0
```


| [Impacted Files](https://codecov.io/gh/zero-os/0-templates/pull/155?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [templates/zrobot/zrobot.py](https://codecov.io/gh/zero-os/0-templates/pull/155/diff?src=pr&el=tree#diff-dGVtcGxhdGVzL3pyb2JvdC96cm9ib3QucHk=) | `64% <16%> (ø)` | |

------

[Continue to review full report at Codecov](https://codecov.io/gh/zero-os/0-templates/pull/155?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/zero-os/0-templates/pull/155?src=pr&el=footer). Last update [c30a7dc...033fa62](https://codecov.io/gh/zero-os/0-templates/pull/155?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).
*

**Comment by chrisvdg** [comment]
@rkhamis, This is a PR not an issue
https://github.com/zero-os/0-templates/pull/155/files
