### ISSUE TITLE
Active / Active High Available vdisk support

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/0-templates#54]
*Issue migrated from [https://api.github.com/repos/zero-os/0-templates/issues/146](), opened by @FastGeert*

The ZDB qemu BD driver supports a HA setup targetting 2 or 3 three ZDB where:
- 1 or 2 ZDB's store the complete dataset
- 1 erasure codes finished datafiles to a set of HDD based ZDB's

Things that need to be accomplished:
- Make namespace reservations on 2 or three SSD based ZDB's for the active/active setup
- Make namespace reservations on a set of HDD based ZDB's for the erasure coded datafiles
- Perform a weekly checkup of the erasure coded datafiles via the 0-stor client check and heal procedures
- Every 5 minutes the vdisk template should check if there are completed datafiles that need to be pushed to the 0-stor
- The VM and 2 or 3 ssd based ZDB's should each be running on a different physical machines if possible
- If one of the ZDB's was offline, the vdisk should get status degraded, and the vm on its turn should get status degraded. To solve the degraded status, the vm should be stopped, and the datafiles of the ZDB that was offline should be healed by copying it over from the healthy ones, or restoring it from the erasure coded datafiles from 0-stor. Then the vm can be started again with healthy status.

**Comment by rkhamis** [comment]
*commented by @zaibon
What is exactly what you call `0-stor` here? 0-stor is a library to write on a zdb, not a server where you can "push" data.*

**Comment by zaibon** [comment]
This is not needed in our architecture
