### ISSUE TITLE
When a gateway action fails the self.data can be corrupted.

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/0-templates#57]
*Issue migrated from [https://api.github.com/repos/zero-os/0-templates/issues/128](), opened by @grimpy*

Because we add the data of the actions before doing the configure it is possible to corrupt the self.data

The expected behaviour would be to remove the data again when the actions fails (and probably do another deploy) This would also protect us when proxies are added that don't work.

**Comment by rkhamis** [comment]
*commented by @serboctor
Fixed by https://github.com/zero-os/0-templates/pull/133/files*

**Comment by serboctor** [comment]
Note for QA: what is meant by data is corrupted, is that the data in the service is not in-sync with reality. What used to cause this is the fact that we update the service data before executing the needed actions, hence if the actions fails and throws an error, the service data will still contain information that is not in-sync with reality. 
The easiest was to reproduce this is to execute the action `add_http_proxy` and in the proxy you send to the action, use a `host` that doesn't exist. This will cause caddy to fail to start and throw an error. After you see the error, check the service data and the http proxy you sent the action should not be in the data.

**Comment by hossnys** [comment]
verified 
branch : development 
lib : [eeb3c4a](https://github.com/threefoldtech/jumpscale_lib/commit/eeb3c4ab1e44a50b5ad56a3190b73028938bab4d)
prefab: [1574a75](https://github.com/threefoldtech/jumpscale_prefab/commit/1574a75cd680301e82360a91e97c93a154f5405e)
core: [f182ac3](https://github.com/threefoldtech/jumpscale_core/commit/f182ac37b4a284361615fb5372389967b82af1fa)

steps to verify : 
follow the steps to create getway [here](https://github.com/threefoldtech/0-templates/blob/development/templates/gateway/README.md)
then list the getway data:
```
{'data': {'certificates': [],
  'domain': 'lan',
  'hostname': 'mygw',
  'httpproxies': [],
  'networks': [{'config': {'cidr': '10.102.21.200/25',
     'gateway': '10.102.21.201'},
    'id': 'c7c8172af1f387a6',
    'name': 'public',
    'type': 'zerotier'},
   {'config': {'cidr': '10.102.21.1/24'},
    'dhcpserver': {'hosts': [{'hostname': 'myvm',
       'ipaddress': '10.102.21.141',
       'macaddress': '10:bf:48:d6:45:18'}],
     'nameservers': ['1.1.1.1']},
    'id': 'c7c8172af1f387a6',
    'name': 'private',
    'type': 'zerotier'}],
  'portforwards': [{'dstip': '10.102.21.141',
    'dstport': 22,
    'name': 'sshtovm',
    'srcnetwork': 'public',
    'srcport': 34022}],
  'routes': [],
  'status': 'halted',
  'ztIdentity': ''},
 'guid': '552d4a4b-7621-49ac-88a8-527211b628b7',
 'name': 'mygw',
 'public': False,
 'secret': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiI1NTJkNGE0Yi03NjIxLTQ5YWMtODhhOC01MjcyMTFiNjI4YjcifQ.siGSQqLK8Akd5-ZzDgo7e8WpV_7UBErlDgrVtylJtw0',
 'state': [],
 'template': 'github.com/threefoldtech/0-templates/gateway/0.0.1',
 'version': '0.0.1'}

```
then try to add proxy to the getway with wrong host ip  like this :
```
In [130]: gwservice.schedule_action('add_http_proxy',  {'proxy':{
     ...:             'host': '10.0.0.200',
     ...:             'destinations': ['http://{}:8000'.format(vmip)],
     ...:             'types': ['http'],
     ...:             'name': 'httpproxy'}
     ...:         })
     ...:         
Out[130]: add_http_proxy

```
then  try to list the data again you will find that proxy is not added there 
```
n [131]: gwservice.data
Out[131]: 
{'data': {'certificates': [],
  'domain': 'lan',
  'hostname': 'mygw',
  'httpproxies': [],
  'networks': [{'config': {'cidr': '10.102.21.200/25',
     'gateway': '10.102.21.201'},
    'id': 'c7c8172af1f387a6',
    'name': 'public',
    'type': 'zerotier'},
   {'config': {'cidr': '10.102.21.1/24'},
    'dhcpserver': {'hosts': [{'hostname': 'myvm',
       'ipaddress': '10.102.21.141',
       'macaddress': '10:bf:48:d6:45:18'}],
     'nameservers': ['1.1.1.1']},
    'id': 'c7c8172af1f387a6',
    'name': 'private',
    'type': 'zerotier'}],
  'portforwards': [{'dstip': '10.102.21.141',
    'dstport': 22,
    'name': 'sshtovm',
    'srcnetwork': 'public',
    'srcport': 34022}],
  'routes': [],
  'status': 'halted',
  'ztIdentity': ''},
 'guid': '552d4a4b-7621-49ac-88a8-527211b628b7',
 'name': 'mygw',
 'public': False,
 'secret': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiI1NTJkNGE0Yi03NjIxLTQ5YWMtODhhOC01MjcyMTFiNjI4YjcifQ.siGSQqLK8Akd5-ZzDgo7e8WpV_7UBErlDgrVtylJtw0',
 'state': [],
 'template': 'github.com/threefoldtech/0-templates/gateway/0.0.1',
 'version': '0.0.1'}

```
