### ISSUE TITLE
Data repo & config repo support when deploying a 0-robot

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/0-templates#59]
*Issue migrated from [https://api.github.com/repos/zero-os/0-templates/issues/121](), opened by @FastGeert*

Some zero-robot just need to be statefull.

Test the feature by deploying the robot on node a, stop it and deploy another robot with the same config & data repo on node b. All services running on the initial robot should still be there on the new robot on node b.

**Comment by zaibon** [comment]
@Pishoy can you give a  bit more detail here please. Are the git repo properly populated with the service data ? How long did you let the robot on node A run before trying to deploy on node b ?

**Comment by Pishoy** [comment]
@zaibon git repo configured properly (config, data) the same on both nodes , it takes around 5 minutes also we have used `auto-push-interval 1` and the same results

**Comment by BolaNasr** [comment]
@Pishoy  should use  **god mode** to see all service running 
```j.clients.zrobot.new('Bola',data={'url':'http://localhost:6600','god_token_':' your_god_token''})```
### and then 
```zrobot server start -D ssh://git@docs.grid.tf:7022/abdelmab/pola-data.git -C ssh://git@docs.grid.tf:7022/abdelmab/pola-config.git -T git@github.com:threefoldtech/0-templates.git#development  --debug  --auto-push --auto-push-interval 1 --god```
### **then** using **js_shell**
```robot = j.clients.zrobot.robots['pola']```
```robot.services.names```
### you will see all services running
