### ISSUE TITLE
Option to add new ips on a node (on existing interface)

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/0-templates#61]
*Issue migrated from [https://api.github.com/repos/zero-os/0-templates/issues/101](), opened by @LeeSmet*

In my current setup in the lochristi DC, I have a couple of zero os nodes (running with zero robot), which run 2 containers: 
- 1 for the threefold chain production network
- 1 for the threefold chain test network

Both of these containers would ideally run on the same port. As such, the container requires 2 ip addresses. In the past this was achieved by using the client and using a command like `ip addr add 185.69.166.18/24 dev enp1s0`, but on a production node running with zero robot, the client isn't allowed anymore, so the node service should have a method with similar behaviour

**Comment by zaibon** [comment]
possible using the [node_ip](https://github.com/threefoldtech/0-templates/tree/development/templates/node_ip) template
