### ISSUE TITLE
Testing zero-os templates for vms

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/0-templates#62]
*Issue migrated from [https://api.github.com/repos/zero-os/0-templates/issues/95](), opened by @john-kheir*

Please write the needed test cases to cover creating vms with correct params and wrong params (if needed) .. Also cover all actions that can be executed for a vm
Please check: https://github.com/zero-os/0-templates/tree/master/templates/vm

**Comment by zaibon** [comment]
@Dinaamagdy 
Do we already have a test that cover the cases when the zerodb that provide a vdisk is restarted. Which will make the zerodb container to have a new ip, so the vm service should update the zdb address it uses for the vdisk? 
I just had the case and seems the services doesn't handle that too well.

**Comment by Dinaamagdy** [comment]
covered on https://github.com/threefoldtech/0-templates/blob/fix_testcases/tests/integration_tests/testsuite/a_basic/vms_tests.py
