### ISSUE TITLE
node templates: possible to stay in reboot status forever

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/0-templates#63]
*Issue migrated from [https://api.github.com/repos/zero-os/0-templates/issues/36](), opened by @zaibon*

The flow for rebooting is the following:
- reboot actions is schedule on the node service
- reboot status is set
- node reboots
- monitor recurring action checks that the node is reachable and if the reboot status is set,
restart all the containers and vms of the node
- remove the reboot status

In this flow, there is a possibility that the node fails to reboot. in which case, the reboot status will never be removed. This is a situation where the 0-robot can't really do anything for the node anymore.
Maybe we could have some kind of notification systems that notify the owner of the node that something is wrong and the node never managed to get back online.
Not sure this belongs to the node templates though, it feels like this should be handled by something else

**Comment by rkhamis** [comment]
*commented by @serboctor
May be whichever layer is managing the node can keep track of the time since the reboot action was executed, and if it takes too long or exceeds a certain configured time, it can fire up the right notifications?*

**Comment by zaibon** [comment]
We should actually remove this reboot action. 
Rebooting a node should be done by the farmer robot using impi or ractivity.
