### ISSUE TITLE
Public IP reservation

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/0-templates#66]
*Issue migrated from [https://api.github.com/repos/zero-os/farming-robot-templates/issues/2](), opened by @xmonader*

# Goals:
The gateway used in dm templates will be a simplified version of the one defined in zero-os/0-templates

# Requirements:
To accomplish this we need a way for a farmer to register the available Public Networks of his farm and how to connect to them.

# Proposal:
This should be registered as part of the 0boot robot the 0boot robot will add a kernel param to the nodes with the 0boot robot url a node action will be added to request a public IP from the 0boot robot.

cc: @grimpy

**Comment by zaibon** [comment]
this is going to handled differently by the farmer 3bot
