### ISSUE TITLE
monitor logic and self-healing

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/0-templates#74]
*Issue migrated from [https://api.github.com/repos/Jumpscale/digital_me/issues/23](), opened by @zaibon*

Now that we have the basic DM templates. we can start thinking about how to self-heal the different workloads.

TODO @zaibon: write down different healing scenarios

**Comment by zaibon** [comment]
closed in favor of #149, #150, #151, #152, #153, #154, #155
