### ISSUE TITLE
VM with active / active database disk

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/0-templates#75]
*Issue migrated from [https://api.github.com/repos/Jumpscale/digital_me/issues/10](), opened by @FastGeert*

Need to be able to deploy a vm with an active / active database disk

Following things need to happen:
- Allocate ZDB shards on two or three ssd based ZDB's running on different physical machines as the vm.
  - 1 or 2 ZDB's will keep all history local
  - 1 ZDB will move its datafiles to erasure coded 0-stor backend via 0-stor client. Every 5 minutes there must be checked if datafiles can be pushed away.
- Allocate ZDB shards for erasure coded timemachine on a set of hdd based ZDB's. The number of ZDB's needed is depending on the erasure coding configuration specified
- Self healing:
  - SSD shards

... not finished yet

**Comment by zaibon** [comment]
not going to implement active-active, this is not needed in our architecture
