### ISSUE TITLE
Minio / 0-stor metadata in mongodb

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/0-templates#77]
*Issue migrated from [https://api.github.com/repos/Jumpscale/digital_me/issues/8](), opened by @FastGeert*

In order to be able to horizontally scale and to make the Minio redundant we need a metadata store that cam be made available and redundant easily.

See https://github.com/zero-os/mongodb-flist/issues/1 for the flist of mongodb

See also:
![Architecture](https://docs.google.com/drawings/d/e/2PACX-1vRLaXG1BGa7eRTyp356mFkTAUc6L_wa6JIgQeQlA-AZNIkHWJ6TGKApUUoAlLvHWz58FosJS0p6t_Ep/pub?w=960&h=720)

**Comment by zaibon** [comment]
Most probably goint to use 0-db instead.
