### ISSUE TITLE
deployment templates for S3 Servers

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/0-templates#78]
*Issue migrated from [https://api.github.com/repos/Jumpscale/digital_me/issues/1](), opened by @zaibon*

## Requirements

- provisioning with nothing more as using the primitives of TF Grid.
- some basic monitoring
- schedule weekly scrubbing (check if data ok and repair if needed)
- schedule hourly backup of S3 metadata on the dirs (with the info for the obj stor) over restic to another S3 or SSH server.

### From a user perspective:
A user buy some storage capacity, This capacity is reserved in term of 0-db namespace.
S3 is deployed on in a container in a 0-os VM.
Information relevant to connect to the S3 instance is returned to the user.

Architecture:

- S3 process will run into a container into a 0-OS VM
- S3 process will connect to multiple 0-dbs that can run locally or on other nodes
- Gree arrow shows the network flow of the data
- Blue arrows show which robot managed which services

Deployment flow:
- deploy a 0-OS VM
- reserve X number of 0-db namespace on X number of nodes
- Connect to the Node robot of the 0-OS VM and deploy the S3 containers
- S3 container need to have a local disk mounted inside to store the metadata
- The VM robot will be responsible to schedule recurring action inside the S3 container to do scrubbing, backup and monitoring

![s3 infrastructure 1](https://user-images.githubusercontent.com/303164/39864866-56c7369a-544b-11e8-9958-0d7a6912e2f7.png)

**Comment by serboctor** [comment]
Adapt S3 for bancadati network:
- Extend S3 to allow creating the vm with a vxlan nic and retrieve the ip set by the gateway.
- Extend DmVm template to allow creating a vm with a vxlan nic.
- Modify Gateway `add_dhcp` and make ipaddress and macaddress optional, and generate them if they're not supplied.

**Comment by Dina-Abd-Elrahman** [comment]
## Jumpscale Version :

- lib : a9e3663a156b81bcf997042e5fa039dfffe1b1a8
- core : 28515efa893162cfc08cc4e259bc268a4c48ef4d
- prefab : 44e92d0c9e47f663c1ede06e8d8c983905da581d

## Verification Steps  :

when i was trying to deploy zos-vm on top of zos node i found this error 

https://github.com/threefoldtech/jumpscale_lib/issues/139

**Comment by islamTaha12** [comment]
https://github.com/threefoldtech/0-templates/issues/126
