### ISSUE TITLE
Spec for extra routes in 0-GW

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/0-templates#81]
Write down required changes required to reach architecture described here:

![setup](https://user-images.githubusercontent.com/8425762/44045021-a866c9f8-9f27-11e8-820f-a6a8b23caa05.png)

**Comment by grimpy** [comment]
In the above architecture the zero-os gw needs to know how to reach the backend network.
Currently zgw does not allow you to use a default network + public network (conflict in default gw)

So we need to solve this in another way:
Setup a bridge (with nat enabled) on the zos (where the gw will run) with nat enabled and route the traffic of the backend network over this interface.

The public network will become the default gw.

Example routing table in gw:
Assuming backplane subnet 10.107.2.0/24
Extra bridge subnet 10.107.3.0/24
```
public 185.22.22.22/24 default gw 185.22.22.1
private( 192.168.0.1/24 ) 192.168.0.0/24 via dev private
birdged (10.107.3.0/24) 10.107.3.0 via dev bridged
added route: 10.107.2.0 via bridged 
```

**Comment by zaibon** [comment]
To allow to unblock us asap, I'll implement the second proposition.

**Comment by zaibon** [comment]
@grimpy support for route management in gateway templates and bridge management in node have been added in #89 
feel free to re-open is something is still missing
