### ISSUE TITLE
Docs statistics 

### ISSUE THREAD

**Issue by chrisvdg** [threefoldtech/0-templates#91]
Docs for statistics templates could use some improvements.

* DSL example doesn't pass the data into the service creation
* Names for the service in the example could be more human friendly
* Reference to influxdb_Client

**Comment by chrisvdg** [comment]
fixed in https://github.com/threefoldtech/0-templates/commit/259befdcffa2ae909f18958616dc74aba2b21844

**Comment by zaibon** [comment]
Thanks 👍
