### ISSUE TITLE
Review capacity planning logic for the zdb used by minio service.

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/0-templates#98]
The current logic that creates the required number of zdb namespace to be used by minio is the following:
- in the schema we specify the data shard and parity shard number.
- the template then do some magic and come up with a number of zdb 
https://github.com/threefoldtech/0-templates/blob/6586c0327877f926c74f41e9fbcf1c1587717698/templates/s3/s3.py#L165-L175
- Then s3 template create the required number of namespace on X number of zdb. X beeing the number of zdb computed at the previous step.
- Finally, s3 create a minio service and pass the list of all namespace url, so minio knows how to reach the zdb namespaces.
https://github.com/threefoldtech/0-templates/blob/6586c0327877f926c74f41e9fbcf1c1587717698/templates/s3/s3.py#L244-L250

If we then look into the code of the minio SAL we can see that from the list of zdb is used to create the minio configuration using this template: 
```jinja2
namespace: {{namespace}}
password: {{namespace_secret}}
datastor: # required
  shards: # required
{%- for zdb in zdbs %}
    - {{zdb -}}
{% endfor %}
  pipeline:
    block_size: {{block_size}}
    compression: # optional, snappy by default
      type: snappy # snappy is the default, other options: lz4, gzip
      mode: default # default is the default, other options: best_speed, best_compression
    encryption: # optional, disabled by default
      type: aes # aes is the default and only standard option
      private_key: {{private_key}}
    distribution:
      data_shards: {{nr_shards}}
```

In there we see that the config actually doesn't configure 0-stor to use erasure coding/distribution but instead replication. This is show by this config:
```
    distribution:
      data_shards: {{nr_shards}}
```
See the documentation to understand how this config works: https://godoc.org/github.com/zero-os/0-stor/client/datastor/pipeline#ObjectDistributionConfig

So first problem, we use replication when in the s3 template we actually ask for information to configure erasure coding, this is by itself wrong.

If we look to how the SAL actually generating this config from the template, we see this:
```python
 def create_config(self):
        logger.info('Creating minio config for %s' % self.name)
        config = templates.render(
            'minio.conf', namespace=self.namespace, namespace_secret=self.namespace_secret,
            zdbs=self.zdbs, private_key=self.private_key, block_size=self.block_size, nr_shards=len(self.zdbs)).strip()
        self.container.upload_content(j.sal.fs.joinPaths(self._config_dir, self._config_name), config)
```

The interesting part here is `nr_shards=len(self.zdbs))`. By configuring the `nr_shards` equal to the number of zerodb namespace available, We tell 0-stor that for a write to be valid, it needs to replicate the data `nr_shards`  time. So in this case it needs to write on all the available shards to mark the write as successful. Which means, if any of the zdb is not reachable, the write will always fail ! This is of course not the intention, the idea is that we have a list of zdb we can use, and we try to write to **some** of them, not all of them. So if some zdb dies, the system keeps working.

## What needs to be done:
- [x] For now, we won't let the user choose the distribution policy of 0-stor. So the s3 template should not accept data_shards, policy_shards anymore, but instead use a predefined policy.
- [x]  fix the computation of the minimum number of zdb namespace required
  - the minimum is computed by: data + parity  = minimum number of zdb. So for a policy of 6/4 -> 10 zdb are required at minimum for the policy to be fulfilled.
- [x] Change the Minio sal so it support any type of configuration (replication, distribution)
- [x] Update the s3 and minio template so it has the information required by the SAL

Now since we always need more zdb then the policy required, how are we decide how much zdb we're going to use ? A simple solution could be we just take 1.5 time the minimum, so for a policy of 6/4 we would try to use 15 zdb (10 minimum and 5 extra)

**Comment by xmonader** [comment]
This approach sounds okay to me

Coding steps:
- Allow minio.conf to be parameterized on `mode` which is `replication` if number of parity shards is zero or `distribution` if it's greater than zero
- Parameterize the Minio SAL to accept nr_datashards and nr_parityshards `WITH NO LINK TO THE NUMBER OF ZDBs`
- Predefine the policy in S3 template to be 6/4 and pass that along to the minio SAL

**Comment by zaibon** [comment]
> Predefine the policy in S3 template to be 6/4 and pass that along to the minio SAL

I was just using 6/4 as an example, need to find a proper default value for it.

**Comment by zaibon** [comment]
https://github.com/threefoldtech/0-templates/commit/27e4f9a8b6db74ef577627e59fa269a8e3058bdd
https://github.com/threefoldtech/jumpscale_lib/commit/de16428f3f97c81a14f8109196aecad5c7426a36
